// Package pg contains the types for schema 'information_schema'.
package pg

// GENERATED BY XO. DO NOT EDIT.

// CollationTable is the database name for the table.
const CollationTable = "information_schema.collations"

// Collation represents a row from 'information_schema.collations'.
type Collation struct {
	CollationCatalog SQLIdentifier `json:"collation_catalog"` // collation_catalog
	CollationSchema  SQLIdentifier `json:"collation_schema"`  // collation_schema
	CollationName    SQLIdentifier `json:"collation_name"`    // collation_name
	PadAttribute     CharacterData `json:"pad_attribute"`     // pad_attribute
}

// Constants defining each column in the table.
const (
	CollationCollationCatalogField = "collation_catalog"
	CollationCollationSchemaField  = "collation_schema"
	CollationCollationNameField    = "collation_name"
	CollationPadAttributeField     = "pad_attribute"
)

// WhereClauses for every type in Collation.
var (
	CollationCollationCatalogWhere SQLIdentifierField = "collation_catalog"
	CollationCollationSchemaWhere  SQLIdentifierField = "collation_schema"
	CollationCollationNameWhere    SQLIdentifierField = "collation_name"
	CollationPadAttributeWhere     CharacterDataField = "pad_attribute"
)

// QueryOneCollation retrieves a row from 'information_schema.collations' as a Collation.
func QueryOneCollation(db XODB, where WhereClause, order OrderBy) (*Collation, error) {
	const origsqlstr = `SELECT ` +
		`collation_catalog, collation_schema, collation_name, pad_attribute ` +
		`FROM information_schema.collations WHERE (`

	idx := 1
	sqlstr := origsqlstr + where.String(&idx) + ") " + order.String() + " LIMIT 1"

	c := &Collation{}
	err := db.QueryRow(sqlstr, where.Values()...).Scan(&c.CollationCatalog, &c.CollationSchema, &c.CollationName, &c.PadAttribute)
	if err != nil {
		return nil, err
	}
	return c, nil
}

// QueryCollation retrieves rows from 'information_schema.collations' as a slice of Collation.
func QueryCollation(db XODB, where WhereClause, order OrderBy) ([]*Collation, error) {
	const origsqlstr = `SELECT ` +
		`collation_catalog, collation_schema, collation_name, pad_attribute ` +
		`FROM information_schema.collations WHERE (`

	idx := 1
	sqlstr := origsqlstr + where.String(&idx) + ") " + order.String()

	var vals []*Collation
	q, err := db.Query(sqlstr, where.Values()...)
	if err != nil {
		return nil, err
	}
	for q.Next() {
		c := Collation{}

		err = q.Scan(&c.CollationCatalog, &c.CollationSchema, &c.CollationName, &c.PadAttribute)
		if err != nil {
			return nil, err
		}

		vals = append(vals, &c)
	}
	return vals, nil
}
