// Package pg contains the types for schema 'information_schema'.
package pg

// GENERATED BY XO. DO NOT EDIT.

// RoleUsageGrantTable is the database name for the table.
const RoleUsageGrantTable = "information_schema.role_usage_grants"

// RoleUsageGrant represents a row from 'information_schema.role_usage_grants'.
type RoleUsageGrant struct {
	Grantor       SQLIdentifier `json:"grantor"`        // grantor
	Grantee       SQLIdentifier `json:"grantee"`        // grantee
	ObjectCatalog SQLIdentifier `json:"object_catalog"` // object_catalog
	ObjectSchema  SQLIdentifier `json:"object_schema"`  // object_schema
	ObjectName    SQLIdentifier `json:"object_name"`    // object_name
	ObjectType    CharacterData `json:"object_type"`    // object_type
	PrivilegeType CharacterData `json:"privilege_type"` // privilege_type
	IsGrantable   YesOrNo       `json:"is_grantable"`   // is_grantable
}

// Constants defining each column in the table.
const (
	RoleUsageGrantGrantorField       = "grantor"
	RoleUsageGrantGranteeField       = "grantee"
	RoleUsageGrantObjectCatalogField = "object_catalog"
	RoleUsageGrantObjectSchemaField  = "object_schema"
	RoleUsageGrantObjectNameField    = "object_name"
	RoleUsageGrantObjectTypeField    = "object_type"
	RoleUsageGrantPrivilegeTypeField = "privilege_type"
	RoleUsageGrantIsGrantableField   = "is_grantable"
)

// WhereClauses for every type in RoleUsageGrant.
var (
	RoleUsageGrantGrantorWhere       SQLIdentifierField = "grantor"
	RoleUsageGrantGranteeWhere       SQLIdentifierField = "grantee"
	RoleUsageGrantObjectCatalogWhere SQLIdentifierField = "object_catalog"
	RoleUsageGrantObjectSchemaWhere  SQLIdentifierField = "object_schema"
	RoleUsageGrantObjectNameWhere    SQLIdentifierField = "object_name"
	RoleUsageGrantObjectTypeWhere    CharacterDataField = "object_type"
	RoleUsageGrantPrivilegeTypeWhere CharacterDataField = "privilege_type"
	RoleUsageGrantIsGrantableWhere   YesOrNoField       = "is_grantable"
)

// QueryOneRoleUsageGrant retrieves a row from 'information_schema.role_usage_grants' as a RoleUsageGrant.
func QueryOneRoleUsageGrant(db XODB, where WhereClause, order OrderBy) (*RoleUsageGrant, error) {
	const origsqlstr = `SELECT ` +
		`grantor, grantee, object_catalog, object_schema, object_name, object_type, privilege_type, is_grantable ` +
		`FROM information_schema.role_usage_grants WHERE (`

	idx := 1
	sqlstr := origsqlstr + where.String(&idx) + ") " + order.String() + " LIMIT 1"

	rug := &RoleUsageGrant{}
	err := db.QueryRow(sqlstr, where.Values()...).Scan(&rug.Grantor, &rug.Grantee, &rug.ObjectCatalog, &rug.ObjectSchema, &rug.ObjectName, &rug.ObjectType, &rug.PrivilegeType, &rug.IsGrantable)
	if err != nil {
		return nil, err
	}
	return rug, nil
}

// QueryRoleUsageGrant retrieves rows from 'information_schema.role_usage_grants' as a slice of RoleUsageGrant.
func QueryRoleUsageGrant(db XODB, where WhereClause, order OrderBy) ([]*RoleUsageGrant, error) {
	const origsqlstr = `SELECT ` +
		`grantor, grantee, object_catalog, object_schema, object_name, object_type, privilege_type, is_grantable ` +
		`FROM information_schema.role_usage_grants WHERE (`

	idx := 1
	sqlstr := origsqlstr + where.String(&idx) + ") " + order.String()

	var vals []*RoleUsageGrant
	q, err := db.Query(sqlstr, where.Values()...)
	if err != nil {
		return nil, err
	}
	for q.Next() {
		rug := RoleUsageGrant{}

		err = q.Scan(&rug.Grantor, &rug.Grantee, &rug.ObjectCatalog, &rug.ObjectSchema, &rug.ObjectName, &rug.ObjectType, &rug.PrivilegeType, &rug.IsGrantable)
		if err != nil {
			return nil, err
		}

		vals = append(vals, &rug)
	}
	return vals, nil
}
