// Package pg contains the types for schema 'information_schema'.
package pg

// GENERATED BY XO. DO NOT EDIT.

import (
	"github.com/pkg/errors"
)

// TablePrivilegeTable is the database name for the table.
const TablePrivilegeTable = "information_schema.table_privileges"

// TablePrivilege represents a row from 'information_schema.table_privileges'.
type TablePrivilege struct {
	Grantor       SQLIdentifier `json:"grantor"`        // grantor
	Grantee       SQLIdentifier `json:"grantee"`        // grantee
	TableCatalog  SQLIdentifier `json:"table_catalog"`  // table_catalog
	TableSchema   SQLIdentifier `json:"table_schema"`   // table_schema
	TableName     SQLIdentifier `json:"table_name"`     // table_name
	PrivilegeType CharacterData `json:"privilege_type"` // privilege_type
	IsGrantable   YesOrNo       `json:"is_grantable"`   // is_grantable
	WithHierarchy YesOrNo       `json:"with_hierarchy"` // with_hierarchy
}

// Constants defining each column in the table.
const (
	TablePrivilegeGrantorField       = "grantor"
	TablePrivilegeGranteeField       = "grantee"
	TablePrivilegeTableCatalogField  = "table_catalog"
	TablePrivilegeTableSchemaField   = "table_schema"
	TablePrivilegeTableNameField     = "table_name"
	TablePrivilegePrivilegeTypeField = "privilege_type"
	TablePrivilegeIsGrantableField   = "is_grantable"
	TablePrivilegeWithHierarchyField = "with_hierarchy"
)

// WhereClauses for every type in TablePrivilege.
var (
	TablePrivilegeGrantorWhere       SQLIdentifierField = "grantor"
	TablePrivilegeGranteeWhere       SQLIdentifierField = "grantee"
	TablePrivilegeTableCatalogWhere  SQLIdentifierField = "table_catalog"
	TablePrivilegeTableSchemaWhere   SQLIdentifierField = "table_schema"
	TablePrivilegeTableNameWhere     SQLIdentifierField = "table_name"
	TablePrivilegePrivilegeTypeWhere CharacterDataField = "privilege_type"
	TablePrivilegeIsGrantableWhere   YesOrNoField       = "is_grantable"
	TablePrivilegeWithHierarchyWhere YesOrNoField       = "with_hierarchy"
)

// QueryOneTablePrivilege retrieves a row from 'information_schema.table_privileges' as a TablePrivilege.
func QueryOneTablePrivilege(db XODB, where WhereClause, order OrderBy) (*TablePrivilege, error) {
	const origsqlstr = `SELECT ` +
		`grantor, grantee, table_catalog, table_schema, table_name, privilege_type, is_grantable, with_hierarchy ` +
		`FROM information_schema.table_privileges WHERE (`

	idx := 1
	sqlstr := origsqlstr + where.String(&idx) + ") " + order.String() + " LIMIT 1"

	tp := &TablePrivilege{}
	err := db.QueryRow(sqlstr, where.Values()...).Scan(&tp.Grantor, &tp.Grantee, &tp.TableCatalog, &tp.TableSchema, &tp.TableName, &tp.PrivilegeType, &tp.IsGrantable, &tp.WithHierarchy)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	return tp, nil
}

// QueryTablePrivilege retrieves rows from 'information_schema.table_privileges' as a slice of TablePrivilege.
func QueryTablePrivilege(db XODB, where WhereClause, order OrderBy) ([]*TablePrivilege, error) {
	const origsqlstr = `SELECT ` +
		`grantor, grantee, table_catalog, table_schema, table_name, privilege_type, is_grantable, with_hierarchy ` +
		`FROM information_schema.table_privileges WHERE (`

	idx := 1
	sqlstr := origsqlstr + where.String(&idx) + ") " + order.String()

	var vals []*TablePrivilege
	q, err := db.Query(sqlstr, where.Values()...)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	for q.Next() {
		tp := TablePrivilege{}

		err = q.Scan(&tp.Grantor, &tp.Grantee, &tp.TableCatalog, &tp.TableSchema, &tp.TableName, &tp.PrivilegeType, &tp.IsGrantable, &tp.WithHierarchy)
		if err != nil {
			return nil, errors.WithStack(err)
		}

		vals = append(vals, &tp)
	}
	return vals, nil
}

// AllTablePrivilege retrieves all rows from 'information_schema.table_privileges' as a slice of TablePrivilege.
func AllTablePrivilege(db XODB, order OrderBy) ([]*TablePrivilege, error) {
	const origsqlstr = `SELECT ` +
		`grantor, grantee, table_catalog, table_schema, table_name, privilege_type, is_grantable, with_hierarchy ` +
		`FROM information_schema.table_privileges`

	sqlstr := origsqlstr + order.String()

	var vals []*TablePrivilege
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	for q.Next() {
		tp := TablePrivilege{}

		err = q.Scan(&tp.Grantor, &tp.Grantee, &tp.TableCatalog, &tp.TableSchema, &tp.TableName, &tp.PrivilegeType, &tp.IsGrantable, &tp.WithHierarchy)
		if err != nil {
			return nil, errors.WithStack(err)
		}

		vals = append(vals, &tp)
	}
	return vals, nil
}
