#
# Generation de code automatisée
#
ConnStr = "sqlserver://user:pass@server/instance?database=db&connection+timeout=30"
DBType = "mssql"
Schemas = ["dbo"]
PluginDirs = ["plugins"]

NameConversion = "{{.}}"
IncludeTables = []
ExcludeTables = []
OutputDir = "output"

NoOverwriteGlobs = ["*.perm.go"]
[TablePaths]


[ProcPaths]
# "{{.Table}}.go" = "template/table.tpl"

"Proc/{{.Proc}}.txt" = "template/proc.tpl"

[SchemaPaths]
# "{{.Schema}}.go" = "template/schema.tpl"


[EnumPaths]
# "{{.Schema}}/enums/{{.Enum}}.go" = "template/enum.tpl"

[TypeMap]
"int" = "int"
"bigint" = "long"
"nvarchar" = "string"
"nchar" = "string"
"bit" = "bool"
"datetime" = "DateTime"
"varbinary" = "byte[]"
"decimal" = "double"
"geography" = "SqlGeography"
"char" = "string"
"date" = "DateTime"

[NullableTypeMap]
"int" = "int?"
"bigint" = "long?"
"nvarchar" = "string?"
"nchar" = "string?"
"bit" = "bool?"
"datetime" = "DateTime?"
"varbinary" = "byte[]?"
"decimal" = "double?"
"geography" = "SqlGeography?"
"float" = "double"
"char" = "string?"
"date" = "DateTime?"

[Params]
mySpecialValue = "some value"
