// Package pg contains the types for schema 'information_schema'.
package pg

// GENERATED BY XO. DO NOT EDIT.

import (
	"github.com/pkg/errors"
)

// AttributeTable is the database name for the table.
const AttributeTable = "information_schema.attributes"

// Attribute represents a row from 'information_schema.attributes'.
type Attribute struct {
	UdtCatalog                  SQLIdentifier  `yaml:"udt_catalog,omitempty"`                    // udt_catalog
	UdtSchema                   SQLIdentifier  `yaml:"udt_schema,omitempty"`                     // udt_schema
	UdtName                     SQLIdentifier  `yaml:"udt_name,omitempty"`                       // udt_name
	AttributeName               SQLIdentifier  `yaml:"attribute_name,omitempty"`                 // attribute_name
	OrdinalPosition             CardinalNumber `yaml:"ordinal_position,omitempty"`               // ordinal_position
	AttributeDefault            CharacterData  `yaml:"attribute_default,omitempty"`              // attribute_default
	IsNullable                  YesOrNo        `yaml:"is_nullable,omitempty"`                    // is_nullable
	DataType                    CharacterData  `yaml:"data_type,omitempty"`                      // data_type
	CharacterMaximumLength      CardinalNumber `yaml:"character_maximum_length,omitempty"`       // character_maximum_length
	CharacterOctetLength        CardinalNumber `yaml:"character_octet_length,omitempty"`         // character_octet_length
	CharacterSetCatalog         SQLIdentifier  `yaml:"character_set_catalog,omitempty"`          // character_set_catalog
	CharacterSetSchema          SQLIdentifier  `yaml:"character_set_schema,omitempty"`           // character_set_schema
	CharacterSetName            SQLIdentifier  `yaml:"character_set_name,omitempty"`             // character_set_name
	CollationCatalog            SQLIdentifier  `yaml:"collation_catalog,omitempty"`              // collation_catalog
	CollationSchema             SQLIdentifier  `yaml:"collation_schema,omitempty"`               // collation_schema
	CollationName               SQLIdentifier  `yaml:"collation_name,omitempty"`                 // collation_name
	NumericPrecision            CardinalNumber `yaml:"numeric_precision,omitempty"`              // numeric_precision
	NumericPrecisionRadix       CardinalNumber `yaml:"numeric_precision_radix,omitempty"`        // numeric_precision_radix
	NumericScale                CardinalNumber `yaml:"numeric_scale,omitempty"`                  // numeric_scale
	DatetimePrecision           CardinalNumber `yaml:"datetime_precision,omitempty"`             // datetime_precision
	IntervalType                CharacterData  `yaml:"interval_type,omitempty"`                  // interval_type
	IntervalPrecision           CardinalNumber `yaml:"interval_precision,omitempty"`             // interval_precision
	AttributeUdtCatalog         SQLIdentifier  `yaml:"attribute_udt_catalog,omitempty"`          // attribute_udt_catalog
	AttributeUdtSchema          SQLIdentifier  `yaml:"attribute_udt_schema,omitempty"`           // attribute_udt_schema
	AttributeUdtName            SQLIdentifier  `yaml:"attribute_udt_name,omitempty"`             // attribute_udt_name
	ScopeCatalog                SQLIdentifier  `yaml:"scope_catalog,omitempty"`                  // scope_catalog
	ScopeSchema                 SQLIdentifier  `yaml:"scope_schema,omitempty"`                   // scope_schema
	ScopeName                   SQLIdentifier  `yaml:"scope_name,omitempty"`                     // scope_name
	MaximumCardinality          CardinalNumber `yaml:"maximum_cardinality,omitempty"`            // maximum_cardinality
	DtdIdentifier               SQLIdentifier  `yaml:"dtd_identifier,omitempty"`                 // dtd_identifier
	IsDerivedReferenceAttribute YesOrNo        `yaml:"is_derived_reference_attribute,omitempty"` // is_derived_reference_attribute
}

// Constants defining each column in the table.
const (
	AttributeUdtCatalogField                  = "udt_catalog"
	AttributeUdtSchemaField                   = "udt_schema"
	AttributeUdtNameField                     = "udt_name"
	AttributeAttributeNameField               = "attribute_name"
	AttributeOrdinalPositionField             = "ordinal_position"
	AttributeAttributeDefaultField            = "attribute_default"
	AttributeIsNullableField                  = "is_nullable"
	AttributeDataTypeField                    = "data_type"
	AttributeCharacterMaximumLengthField      = "character_maximum_length"
	AttributeCharacterOctetLengthField        = "character_octet_length"
	AttributeCharacterSetCatalogField         = "character_set_catalog"
	AttributeCharacterSetSchemaField          = "character_set_schema"
	AttributeCharacterSetNameField            = "character_set_name"
	AttributeCollationCatalogField            = "collation_catalog"
	AttributeCollationSchemaField             = "collation_schema"
	AttributeCollationNameField               = "collation_name"
	AttributeNumericPrecisionField            = "numeric_precision"
	AttributeNumericPrecisionRadixField       = "numeric_precision_radix"
	AttributeNumericScaleField                = "numeric_scale"
	AttributeDatetimePrecisionField           = "datetime_precision"
	AttributeIntervalTypeField                = "interval_type"
	AttributeIntervalPrecisionField           = "interval_precision"
	AttributeAttributeUdtCatalogField         = "attribute_udt_catalog"
	AttributeAttributeUdtSchemaField          = "attribute_udt_schema"
	AttributeAttributeUdtNameField            = "attribute_udt_name"
	AttributeScopeCatalogField                = "scope_catalog"
	AttributeScopeSchemaField                 = "scope_schema"
	AttributeScopeNameField                   = "scope_name"
	AttributeMaximumCardinalityField          = "maximum_cardinality"
	AttributeDtdIdentifierField               = "dtd_identifier"
	AttributeIsDerivedReferenceAttributeField = "is_derived_reference_attribute"
)

// WhereClauses for every type in Attribute.
var (
	AttributeUdtCatalogWhere                  SQLIdentifierField  = "udt_catalog"
	AttributeUdtSchemaWhere                   SQLIdentifierField  = "udt_schema"
	AttributeUdtNameWhere                     SQLIdentifierField  = "udt_name"
	AttributeAttributeNameWhere               SQLIdentifierField  = "attribute_name"
	AttributeOrdinalPositionWhere             CardinalNumberField = "ordinal_position"
	AttributeAttributeDefaultWhere            CharacterDataField  = "attribute_default"
	AttributeIsNullableWhere                  YesOrNoField        = "is_nullable"
	AttributeDataTypeWhere                    CharacterDataField  = "data_type"
	AttributeCharacterMaximumLengthWhere      CardinalNumberField = "character_maximum_length"
	AttributeCharacterOctetLengthWhere        CardinalNumberField = "character_octet_length"
	AttributeCharacterSetCatalogWhere         SQLIdentifierField  = "character_set_catalog"
	AttributeCharacterSetSchemaWhere          SQLIdentifierField  = "character_set_schema"
	AttributeCharacterSetNameWhere            SQLIdentifierField  = "character_set_name"
	AttributeCollationCatalogWhere            SQLIdentifierField  = "collation_catalog"
	AttributeCollationSchemaWhere             SQLIdentifierField  = "collation_schema"
	AttributeCollationNameWhere               SQLIdentifierField  = "collation_name"
	AttributeNumericPrecisionWhere            CardinalNumberField = "numeric_precision"
	AttributeNumericPrecisionRadixWhere       CardinalNumberField = "numeric_precision_radix"
	AttributeNumericScaleWhere                CardinalNumberField = "numeric_scale"
	AttributeDatetimePrecisionWhere           CardinalNumberField = "datetime_precision"
	AttributeIntervalTypeWhere                CharacterDataField  = "interval_type"
	AttributeIntervalPrecisionWhere           CardinalNumberField = "interval_precision"
	AttributeAttributeUdtCatalogWhere         SQLIdentifierField  = "attribute_udt_catalog"
	AttributeAttributeUdtSchemaWhere          SQLIdentifierField  = "attribute_udt_schema"
	AttributeAttributeUdtNameWhere            SQLIdentifierField  = "attribute_udt_name"
	AttributeScopeCatalogWhere                SQLIdentifierField  = "scope_catalog"
	AttributeScopeSchemaWhere                 SQLIdentifierField  = "scope_schema"
	AttributeScopeNameWhere                   SQLIdentifierField  = "scope_name"
	AttributeMaximumCardinalityWhere          CardinalNumberField = "maximum_cardinality"
	AttributeDtdIdentifierWhere               SQLIdentifierField  = "dtd_identifier"
	AttributeIsDerivedReferenceAttributeWhere YesOrNoField        = "is_derived_reference_attribute"
)

// QueryOneAttribute retrieves a row from 'information_schema.attributes' as a Attribute.
func QueryOneAttribute(db XODB, where WhereClause, order OrderBy) (*Attribute, error) {
	const origsqlstr = `SELECT ` +
		`udt_catalog, udt_schema, udt_name, attribute_name, ordinal_position, attribute_default, is_nullable, data_type, character_maximum_length, character_octet_length, character_set_catalog, character_set_schema, character_set_name, collation_catalog, collation_schema, collation_name, numeric_precision, numeric_precision_radix, numeric_scale, datetime_precision, interval_type, interval_precision, attribute_udt_catalog, attribute_udt_schema, attribute_udt_name, scope_catalog, scope_schema, scope_name, maximum_cardinality, dtd_identifier, is_derived_reference_attribute ` +
		`FROM information_schema.attributes WHERE (`

	idx := 1
	sqlstr := origsqlstr + where.String(&idx) + ") " + order.String() + " LIMIT 1"

	a := &Attribute{}
	err := db.QueryRow(sqlstr, where.Values()...).Scan(&a.UdtCatalog, &a.UdtSchema, &a.UdtName, &a.AttributeName, &a.OrdinalPosition, &a.AttributeDefault, &a.IsNullable, &a.DataType, &a.CharacterMaximumLength, &a.CharacterOctetLength, &a.CharacterSetCatalog, &a.CharacterSetSchema, &a.CharacterSetName, &a.CollationCatalog, &a.CollationSchema, &a.CollationName, &a.NumericPrecision, &a.NumericPrecisionRadix, &a.NumericScale, &a.DatetimePrecision, &a.IntervalType, &a.IntervalPrecision, &a.AttributeUdtCatalog, &a.AttributeUdtSchema, &a.AttributeUdtName, &a.ScopeCatalog, &a.ScopeSchema, &a.ScopeName, &a.MaximumCardinality, &a.DtdIdentifier, &a.IsDerivedReferenceAttribute)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	return a, nil
}

// QueryAttribute retrieves rows from 'information_schema.attributes' as a slice of Attribute.
func QueryAttribute(db XODB, where WhereClause, order OrderBy) ([]*Attribute, error) {
	const origsqlstr = `SELECT ` +
		`udt_catalog, udt_schema, udt_name, attribute_name, ordinal_position, attribute_default, is_nullable, data_type, character_maximum_length, character_octet_length, character_set_catalog, character_set_schema, character_set_name, collation_catalog, collation_schema, collation_name, numeric_precision, numeric_precision_radix, numeric_scale, datetime_precision, interval_type, interval_precision, attribute_udt_catalog, attribute_udt_schema, attribute_udt_name, scope_catalog, scope_schema, scope_name, maximum_cardinality, dtd_identifier, is_derived_reference_attribute ` +
		`FROM information_schema.attributes WHERE (`

	idx := 1
	sqlstr := origsqlstr + where.String(&idx) + ") " + order.String()

	var vals []*Attribute
	q, err := db.Query(sqlstr, where.Values()...)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	for q.Next() {
		a := Attribute{}

		err = q.Scan(&a.UdtCatalog, &a.UdtSchema, &a.UdtName, &a.AttributeName, &a.OrdinalPosition, &a.AttributeDefault, &a.IsNullable, &a.DataType, &a.CharacterMaximumLength, &a.CharacterOctetLength, &a.CharacterSetCatalog, &a.CharacterSetSchema, &a.CharacterSetName, &a.CollationCatalog, &a.CollationSchema, &a.CollationName, &a.NumericPrecision, &a.NumericPrecisionRadix, &a.NumericScale, &a.DatetimePrecision, &a.IntervalType, &a.IntervalPrecision, &a.AttributeUdtCatalog, &a.AttributeUdtSchema, &a.AttributeUdtName, &a.ScopeCatalog, &a.ScopeSchema, &a.ScopeName, &a.MaximumCardinality, &a.DtdIdentifier, &a.IsDerivedReferenceAttribute)
		if err != nil {
			return nil, errors.WithStack(err)
		}

		vals = append(vals, &a)
	}
	return vals, nil
}

// AllAttribute retrieves all rows from 'information_schema.attributes' as a slice of Attribute.
func AllAttribute(db XODB, order OrderBy) ([]*Attribute, error) {
	const origsqlstr = `SELECT ` +
		`udt_catalog, udt_schema, udt_name, attribute_name, ordinal_position, attribute_default, is_nullable, data_type, character_maximum_length, character_octet_length, character_set_catalog, character_set_schema, character_set_name, collation_catalog, collation_schema, collation_name, numeric_precision, numeric_precision_radix, numeric_scale, datetime_precision, interval_type, interval_precision, attribute_udt_catalog, attribute_udt_schema, attribute_udt_name, scope_catalog, scope_schema, scope_name, maximum_cardinality, dtd_identifier, is_derived_reference_attribute ` +
		`FROM information_schema.attributes`

	sqlstr := origsqlstr + order.String()

	var vals []*Attribute
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	for q.Next() {
		a := Attribute{}

		err = q.Scan(&a.UdtCatalog, &a.UdtSchema, &a.UdtName, &a.AttributeName, &a.OrdinalPosition, &a.AttributeDefault, &a.IsNullable, &a.DataType, &a.CharacterMaximumLength, &a.CharacterOctetLength, &a.CharacterSetCatalog, &a.CharacterSetSchema, &a.CharacterSetName, &a.CollationCatalog, &a.CollationSchema, &a.CollationName, &a.NumericPrecision, &a.NumericPrecisionRadix, &a.NumericScale, &a.DatetimePrecision, &a.IntervalType, &a.IntervalPrecision, &a.AttributeUdtCatalog, &a.AttributeUdtSchema, &a.AttributeUdtName, &a.ScopeCatalog, &a.ScopeSchema, &a.ScopeName, &a.MaximumCardinality, &a.DtdIdentifier, &a.IsDerivedReferenceAttribute)
		if err != nil {
			return nil, errors.WithStack(err)
		}

		vals = append(vals, &a)
	}
	return vals, nil
}
