// Package pg contains the types for schema 'information_schema'.
package pg

// GENERATED BY XO. DO NOT EDIT.

import (
	"github.com/pkg/errors"
)

// RoleTableGrantTable is the database name for the table.
const RoleTableGrantTable = "information_schema.role_table_grants"

// RoleTableGrant represents a row from 'information_schema.role_table_grants'.
type RoleTableGrant struct {
	Grantor       SQLIdentifier `yaml:"grantor,omitempty"`        // grantor
	Grantee       SQLIdentifier `yaml:"grantee,omitempty"`        // grantee
	TableCatalog  SQLIdentifier `yaml:"table_catalog,omitempty"`  // table_catalog
	TableSchema   SQLIdentifier `yaml:"table_schema,omitempty"`   // table_schema
	TableName     SQLIdentifier `yaml:"table_name,omitempty"`     // table_name
	PrivilegeType CharacterData `yaml:"privilege_type,omitempty"` // privilege_type
	IsGrantable   YesOrNo       `yaml:"is_grantable,omitempty"`   // is_grantable
	WithHierarchy YesOrNo       `yaml:"with_hierarchy,omitempty"` // with_hierarchy
}

// Constants defining each column in the table.
const (
	RoleTableGrantGrantorField       = "grantor"
	RoleTableGrantGranteeField       = "grantee"
	RoleTableGrantTableCatalogField  = "table_catalog"
	RoleTableGrantTableSchemaField   = "table_schema"
	RoleTableGrantTableNameField     = "table_name"
	RoleTableGrantPrivilegeTypeField = "privilege_type"
	RoleTableGrantIsGrantableField   = "is_grantable"
	RoleTableGrantWithHierarchyField = "with_hierarchy"
)

// WhereClauses for every type in RoleTableGrant.
var (
	RoleTableGrantGrantorWhere       SQLIdentifierField = "grantor"
	RoleTableGrantGranteeWhere       SQLIdentifierField = "grantee"
	RoleTableGrantTableCatalogWhere  SQLIdentifierField = "table_catalog"
	RoleTableGrantTableSchemaWhere   SQLIdentifierField = "table_schema"
	RoleTableGrantTableNameWhere     SQLIdentifierField = "table_name"
	RoleTableGrantPrivilegeTypeWhere CharacterDataField = "privilege_type"
	RoleTableGrantIsGrantableWhere   YesOrNoField       = "is_grantable"
	RoleTableGrantWithHierarchyWhere YesOrNoField       = "with_hierarchy"
)

// QueryOneRoleTableGrant retrieves a row from 'information_schema.role_table_grants' as a RoleTableGrant.
func QueryOneRoleTableGrant(db XODB, where WhereClause, order OrderBy) (*RoleTableGrant, error) {
	const origsqlstr = `SELECT ` +
		`grantor, grantee, table_catalog, table_schema, table_name, privilege_type, is_grantable, with_hierarchy ` +
		`FROM information_schema.role_table_grants WHERE (`

	idx := 1
	sqlstr := origsqlstr + where.String(&idx) + ") " + order.String() + " LIMIT 1"

	rtg := &RoleTableGrant{}
	err := db.QueryRow(sqlstr, where.Values()...).Scan(&rtg.Grantor, &rtg.Grantee, &rtg.TableCatalog, &rtg.TableSchema, &rtg.TableName, &rtg.PrivilegeType, &rtg.IsGrantable, &rtg.WithHierarchy)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	return rtg, nil
}

// QueryRoleTableGrant retrieves rows from 'information_schema.role_table_grants' as a slice of RoleTableGrant.
func QueryRoleTableGrant(db XODB, where WhereClause, order OrderBy) ([]*RoleTableGrant, error) {
	const origsqlstr = `SELECT ` +
		`grantor, grantee, table_catalog, table_schema, table_name, privilege_type, is_grantable, with_hierarchy ` +
		`FROM information_schema.role_table_grants WHERE (`

	idx := 1
	sqlstr := origsqlstr + where.String(&idx) + ") " + order.String()

	var vals []*RoleTableGrant
	q, err := db.Query(sqlstr, where.Values()...)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	for q.Next() {
		rtg := RoleTableGrant{}

		err = q.Scan(&rtg.Grantor, &rtg.Grantee, &rtg.TableCatalog, &rtg.TableSchema, &rtg.TableName, &rtg.PrivilegeType, &rtg.IsGrantable, &rtg.WithHierarchy)
		if err != nil {
			return nil, errors.WithStack(err)
		}

		vals = append(vals, &rtg)
	}
	return vals, nil
}

// AllRoleTableGrant retrieves all rows from 'information_schema.role_table_grants' as a slice of RoleTableGrant.
func AllRoleTableGrant(db XODB, order OrderBy) ([]*RoleTableGrant, error) {
	const origsqlstr = `SELECT ` +
		`grantor, grantee, table_catalog, table_schema, table_name, privilege_type, is_grantable, with_hierarchy ` +
		`FROM information_schema.role_table_grants`

	sqlstr := origsqlstr + order.String()

	var vals []*RoleTableGrant
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	for q.Next() {
		rtg := RoleTableGrant{}

		err = q.Scan(&rtg.Grantor, &rtg.Grantee, &rtg.TableCatalog, &rtg.TableSchema, &rtg.TableName, &rtg.PrivilegeType, &rtg.IsGrantable, &rtg.WithHierarchy)
		if err != nil {
			return nil, errors.WithStack(err)
		}

		vals = append(vals, &rtg)
	}
	return vals, nil
}
