// Code generated by gnorm, DO NOT EDIT!

package parameters

import (
	"database/sql"
	"gnorm.org/gnorm/database/drivers/mssql/gnorm"
	"log"
)

// Row represents a row from 'COLUMNS'.
type Row struct {
	ProcCatalog            string         // PROC_CATALOG
	ProcSchema             string         // PROC_SCHEMA
	ProcName               string         // PROC_NAME
	ParameterName          string         // PARAMETER_NAME
	OrdinalPosition        int            // ORDINAL_POSITION
	ParameterDefault       sql.NullString // PARAMETER_DEFAULT
	IsNullable             string         // IS_NULLABLE
	DataType               string         // DATA_TYPE
	NumericPrecision       sql.NullInt64  // NUMERIC_PRECISION
	NumericPrecisionRadix  sql.NullInt64  // NUMERIC_PRECISION_RADIX
	NumericScale           sql.NullInt64  // NUMERIC_SCALE
	DatetimePrecision      sql.NullInt64  // DATETIME_PRECISION
	CharacterMaximumLength sql.NullInt64  // CHARACTER_MAXIMUM_LENGTH
	CharacterSetCatalog    sql.NullString // CHARACTER_SET_CATALOG
	CharacterSetSchema     sql.NullString // CHARACTER_SET_SCHEMA
	CharacterSetName       sql.NullString // CHARACTER_SET_NAME
	CollationCatalog       sql.NullString // COLLATION_CATALOG
	CollationSchema        sql.NullString // COLLATION_SCHEMA
	CollationName          sql.NullString // COLLATION_NAME
	DomainCatalog          sql.NullString // DOMAIN_CATALOG
	DomainSchema           sql.NullString // DOMAIN_SCHEMA
	DomainName             sql.NullString // DOMAIN_NAME
}

// Query retrieves rows from 'COLUMNS' as a slice of Row.
func Query(db gnorm.DB, schema string, proc string) ([]*Row, error) {
	const strsql = `

SELECT p.SPECIFIC_CATALOG,
       p.SPECIFIC_SCHEMA,
	   p.SPECIFIC_NAME,
	   p.PARAMETER_NAME,
	   p.ORDINAL_POSITION,
	   null as PARAMETER_DEFAULT, --p.PARAMETER_DEFAULT,
	   0 as IS_NULLABLE, -- p.IS_NULLABLE,
	   p.DATA_TYPE,
	   p.NUMERIC_PRECISION,
	   p.NUMERIC_PRECISION_RADIX, 
	   p.NUMERIC_SCALE, 
	   p.DATETIME_PRECISION, 
	   p.CHARACTER_MAXIMUM_LENGTH,
	   p.CHARACTER_SET_CATALOG,
	   p.CHARACTER_SET_SCHEMA,
	   p.CHARACTER_SET_NAME,
	   p.COLLATION_CATALOG,
	   p.COLLATION_SCHEMA,
	   p.COLLATION_NAME,
	   null AS DOMAIN_CATALOG, -- c.DOMAIN_CATALOG,
	   null AS DOMAIN_SCHEMA, -- c.DOMAIN_SCHEMA,
	   null AS DOMAIN_NAME -- c.DOMAIN_NAME
 
	FROM INFORMATION_SCHEMA.PARAMETERS p

  WHERE p.SPECIFIC_SCHEMA = @schema
       AND p.SPECIFIC_NAME = @proc

  ;
`
	log.Println("querying parameters ", strsql)
	log.Println("from schema ", schema)
	log.Println("from proc ", proc)

	var vals []*Row
	q, err := db.Query(strsql,
		sql.Named("schema", schema),
		sql.Named("proc", proc),
	)

	if err != nil {
		return nil, err
	}
	for q.Next() {
		r := Row{}

		err = q.Scan(
			&r.ProcCatalog,
			&r.ProcSchema,
			&r.ProcName,
			&r.ParameterName,
			&r.OrdinalPosition,
			&r.ParameterDefault,
			&r.IsNullable,
			&r.DataType,
			&r.NumericPrecision,
			&r.NumericPrecisionRadix,
			&r.NumericScale,
			&r.DatetimePrecision,
			&r.CharacterMaximumLength,
			&r.CharacterSetCatalog,
			&r.CharacterSetSchema,
			&r.CharacterSetName,
			&r.CollationCatalog,
			&r.CollationSchema,
			&r.CollationName,
			&r.DomainCatalog,
			&r.DomainSchema,
			&r.DomainName,
		)
		if err != nil {
			return nil, err
		}

		vals = append(vals, &r)
	}
	return vals, nil
}
